/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Marz Test API
 * Test-only contract for E2E fixtures. All endpoints require `X-Test-Secret`
and are gated by `TEST_API_ENABLED=true`. Never available in production.

Consumed by marz-front E2E suite via a separate Orval generation target so
the production client stays free of test-only types.

 * OpenAPI spec version: 0.1.0
 */

export type BrandAttributionSource = typeof BrandAttributionSource[keyof typeof BrandAttributionSource];


export const BrandAttributionSource = {
  instagram: 'instagram',
  tiktok: 'tiktok',
  linkedin: 'linkedin',
  reddit: 'reddit',
  referral: 'referral',
  search: 'search',
  other: 'other',
} as const;
