/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Marz Test API
 * Test-only contract for E2E fixtures. All endpoints require `X-Test-Secret`
and are gated by `TEST_API_ENABLED=true`. Never available in production.

Consumed by marz-front E2E suite via a separate Orval generation target so
the production client stays free of test-only types.

 * OpenAPI spec version: 0.1.0
 */
import type { BulkSeedInboxItemPayload } from './bulkSeedInboxItemPayload';
import type { InboxItemKind } from './inboxItemKind';
import type { InboxItemSection } from './inboxItemSection';
import type { InboxItemStatus } from './inboxItemStatus';
import type { InboxSourceRef } from './inboxSourceRef';

export interface BulkSeedInboxItem {
  recipient_account_id: string;
  section: InboxItemSection;
  kind: InboxItemKind;
  status: InboxItemStatus;
  occurred_at: string;
  payload: BulkSeedInboxItemPayload;
  source_ref: InboxSourceRef;
  /** @nullable */
  campaign_id?: string | null;
  /** @nullable */
  brand_workspace_id?: string | null;
}
