/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Marz Test API
 * Test-only contract for E2E fixtures. All endpoints require `X-Test-Secret`
and are gated by `TEST_API_ENABLED=true`. Never available in production.

Consumed by marz-front E2E suite via a separate Orval generation target so
the production client stays free of test-only types.

 * OpenAPI spec version: 0.1.0
 */
import type { CreatorProfileBestVideosItem } from './creatorProfileBestVideosItem';

export interface CreatorProfile {
  /** @maxLength 200 */
  handle?: string;
  /** @maxLength 200 */
  display_name?: string;
  /**
     * @maxLength 2000
     * @nullable
     */
  bio?: string | null;
  /** @nullable */
  tier?: string | null;
  niches?: string[];
  content_types?: string[];
  /** @nullable */
  country?: string | null;
  /**
     * @maxLength 200
     * @nullable
     */
  city?: string | null;
  /** @nullable */
  avatar_url?: string | null;
  /** @nullable */
  experience_level?: string | null;
  /** @nullable */
  gender?: string | null;
  /** @nullable */
  birthday?: string | null;
  /** @nullable */
  whatsapp_e164?: string | null;
  /** @nullable */
  referral_text?: string | null;
  best_videos?: CreatorProfileBestVideosItem[];
  /** @nullable */
  onboarded_at?: string | null;
}
