/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Marz Test API
 * Test-only contract for E2E fixtures. All endpoints require `X-Test-Secret`
and are gated by `TEST_API_ENABLED=true`. Never available in production.

Consumed by marz-front E2E suite via a separate Orval generation target so
the production client stays free of test-only types.

 * OpenAPI spec version: 0.1.0
 */
import type { SeedMessagesInput } from './seedMessagesInput'

export interface CreateTestConversationRequest {
  /** @minLength 1 */
  brand_clerk_user_id: string
  /** @minLength 1 */
  creator_clerk_user_id: string
  seed_messages?: SeedMessagesInput
}
