/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Marz Test API
 * Test-only contract for E2E fixtures. All endpoints require `X-Test-Secret`
and are gated by `TEST_API_ENABLED=true`. Never available in production.

Consumed by marz-front E2E suite via a separate Orval generation target so
the production client stays free of test-only types.

 * OpenAPI spec version: 0.1.0
 */

export type InboxItemKind = typeof InboxItemKind[keyof typeof InboxItemKind];


export const InboxItemKind = {
  message_reply: 'message_reply',
  offer_received: 'offer_received',
  offer_sent_waiting: 'offer_sent_waiting',
  draft_review: 'draft_review',
  draft_changes_requested: 'draft_changes_requested',
  draft_sent_waiting: 'draft_sent_waiting',
  draft_approved_publish_link: 'draft_approved_publish_link',
  link_review: 'link_review',
  link_sent_waiting: 'link_sent_waiting',
  link_changes_requested: 'link_changes_requested',
  application_received: 'application_received',
  application_sent_waiting: 'application_sent_waiting',
  match_suggested: 'match_suggested',
  invite_sent_waiting: 'invite_sent_waiting',
  refund_delayed: 'refund_delayed',
} as const;
