/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Marz Test API
 * Test-only contract for E2E fixtures. All endpoints require `X-Test-Secret`
and are gated by `TEST_API_ENABLED=true`. Never available in production.

Consumed by marz-front E2E suite via a separate Orval generation target so
the production client stays free of test-only types.

 * OpenAPI spec version: 0.1.0
 */

export * from './accountKind';
export * from './brandAttributionSource';
export * from './brandWorkspaceSummary';
export * from './bulkSeedInboxItem';
export * from './bulkSeedInboxItemPayload';
export * from './bulkSeedInboxItemsRequest';
export * from './bulkSeedInboxItemsResponse';
export * from './createTestAccountRequest';
export * from './createTestConversationRequest';
export * from './createTestConversationResponse';
export * from './createTestFault200';
export * from './createTestFaultRequest';
export * from './createTestFaultRequestBody';
export * from './createTestFaultRequestCount';
export * from './creatorProfile';
export * from './creatorProfileBestVideosItem';
export * from './emitTestEvent200';
export * from './emitTestEventRequest';
export * from './emitTestEventRequestPayload';
export * from './error';
export * from './errorError';
export * from './errorErrorDetails';
export * from './inboxItemKind';
export * from './inboxItemSection';
export * from './inboxItemStatus';
export * from './inboxSourceRef';
export * from './inboxSourceRefType';
export * from './meResponse';
export * from './onboardingStatus';
export * from './onboardTestAccountFullRequest';
export * from './purgeTestAccountsRequest';
export * from './purgeTestAccountsResponse';
export * from './resetTestWorkspace200';
export * from './resetTestWorkspaceRequest';
export * from './seedMessagesInput';
export * from './seedMessagesInputMarkReadFor';
export * from './seedOfferReadyInput';
export * from './setTestBrandAttributionSourceRequest';
export * from './setTestBrandAttributionSourceResponse';
export * from './setTestInboxItemStatus200';
export * from './setTestInboxItemStatusRequest';
export * from './setTestInboxItemStatusRequestStatus';
export * from './setTestOnboardingRequest';
export * from './testAccountResponse';
export * from './testBrandAttributionSource';
export * from './upsertTestBrandOnboardingProfileRequest';
export * from './upsertTestBrandOnboardingProfileResponse';
export * from './upsertTestCampaignParticipantRequest';
export * from './upsertTestCampaignParticipantRequestCurrentPlatformsItem';
export * from './upsertTestCampaignParticipantRequestSource';
export * from './upsertTestCampaignParticipantRequestStatus';
export * from './upsertTestCampaignParticipantResponse';
export * from './upsertTestCampaignRequest';
export * from './upsertTestCampaignRequestBonusConfig';
export * from './upsertTestCampaignRequestConfigurationCompletedStepsItem';
export * from './upsertTestCampaignRequestConfigurationCurrentStep';
export * from './upsertTestCampaignRequestContentType';
export * from './upsertTestCampaignRequestObjective';
export * from './upsertTestCampaignRequestOperationalTargeting';
export * from './upsertTestCampaignRequestPricingModel';
export * from './upsertTestCampaignRequestStatus';
export * from './upsertTestCampaignResponse';
export * from './upsertTestCampaignVideoRequest';
export * from './upsertTestCampaignVideoRequestPlatform';
export * from './upsertTestCampaignVideoRequestStatus';
export * from './upsertTestCampaignVideoResponse';
