/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Marz Test API
 * Test-only contract for E2E fixtures. All endpoints require `X-Test-Secret`
and are gated by `TEST_API_ENABLED=true`. Never available in production.

Consumed by marz-front E2E suite via a separate Orval generation target so
the production client stays free of test-only types.

 * OpenAPI spec version: 0.1.0
 */
import type { AccountKind } from './accountKind'
import type { BrandWorkspaceSummary } from './brandWorkspaceSummary'
import type { CreatorProfile } from './creatorProfile'
import type { OnboardingStatus } from './onboardingStatus'

export interface MeResponse {
  id: string
  email: string
  kind?: AccountKind | null
  /** @maxLength 200 */
  full_name: string
  /** @nullable */
  verified_at?: string | null
  created_at: string
  /** @nullable */
  redirect_to: string | null
  onboarding_status: OnboardingStatus
  creator_profile?: CreatorProfile | null
  brand_workspace?: BrandWorkspaceSummary | null
}
