/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Marz Test API
 * Test-only contract for E2E fixtures. All endpoints require `X-Test-Secret`
and are gated by `TEST_API_ENABLED=true`. Never available in production.

Consumed by marz-front E2E suite via a separate Orval generation target so
the production client stays free of test-only types.

 * OpenAPI spec version: 0.1.0
 */

export interface PurgeTestAccountsRequest {
  /**
     * SQL LIKE pattern matched against `identity_accounts.email`. Must
  contain at least one wildcard (`%` or `_`). Examples:
  `e2e.%`, `%@e2e.test`, `brand_run42_%@example.com`.

     * @minLength 1
     */
  email_like: string
}
