/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Marz Test API
 * Test-only contract for E2E fixtures. All endpoints require `X-Test-Secret`
and are gated by `TEST_API_ENABLED=true`. Never available in production.

Consumed by marz-front E2E suite via a separate Orval generation target so
the production client stays free of test-only types.

 * OpenAPI spec version: 0.1.0
 */

/**
 * Which side(s) should have read receipts inserted for the seeded
messages. A reader never marks their own messages as read.

 */
export type SeedMessagesInputMarkReadFor =
  (typeof SeedMessagesInputMarkReadFor)[keyof typeof SeedMessagesInputMarkReadFor]

export const SeedMessagesInputMarkReadFor = {
  brand: 'brand',
  creator: 'creator',
  both: 'both',
  none: 'none',
} as const
