/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Marz Test API
 * Test-only contract for E2E fixtures. All endpoints require `X-Test-Secret`
and are gated by `TEST_API_ENABLED=true`. Never available in production.

Consumed by marz-front E2E suite via a separate Orval generation target so
the production client stays free of test-only types.

 * OpenAPI spec version: 0.1.0
 */
import type { SeedMessagesInputMarkReadFor } from './seedMessagesInputMarkReadFor'

export interface SeedMessagesInput {
  /**
   * Number of text messages to seed. Hard cap is 500.
   * @minimum 0
   * @maximum 500
   */
  count: number
  /** When true, message at index 0 is authored by the brand, index 1 by
  the creator, alternating from there.
   */
  alternating_authors?: boolean
  /** Which side(s) should have read receipts inserted for the seeded
  messages. A reader never marks their own messages as read.
   */
  mark_read_for?: SeedMessagesInputMarkReadFor
}
