/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Marz Test API
 * Test-only contract for E2E fixtures. All endpoints require `X-Test-Secret`
and are gated by `TEST_API_ENABLED=true`. Never available in production.

Consumed by marz-front E2E suite via a separate Orval generation target so
the production client stays free of test-only types.

 * OpenAPI spec version: 0.1.0
 */

export type UpsertTestCampaignParticipantRequestStatus = typeof UpsertTestCampaignParticipantRequestStatus[keyof typeof UpsertTestCampaignParticipantRequestStatus];


export const UpsertTestCampaignParticipantRequestStatus = {
  invited: 'invited',
  active: 'active',
  in_review: 'in_review',
  approved: 'approved',
  paid: 'paid',
} as const;
