/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Marz Test API
 * Test-only contract for E2E fixtures. All endpoints require `X-Test-Secret`
and are gated by `TEST_API_ENABLED=true`. Never available in production.

Consumed by marz-front E2E suite via a separate Orval generation target so
the production client stays free of test-only types.

 * OpenAPI spec version: 0.1.0
 */

export type UpsertTestCampaignVideoRequestStatus = typeof UpsertTestCampaignVideoRequestStatus[keyof typeof UpsertTestCampaignVideoRequestStatus];


export const UpsertTestCampaignVideoRequestStatus = {
  pending: 'pending',
  draft_submitted: 'draft_submitted',
  changes_requested: 'changes_requested',
  draft_approved: 'draft_approved',
  link_submitted: 'link_submitted',
  link_approved: 'link_approved',
  completed: 'completed',
  paid: 'paid',
} as const;
