/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Marz Test API
 * Test-only contract for E2E fixtures. All endpoints require `X-Test-Secret`
and are gated by `TEST_API_ENABLED=true`. Never available in production.

Consumed by marz-front E2E suite via a separate Orval generation target so
the production client stays free of test-only types.

 * OpenAPI spec version: 0.1.0
 */
import type { UpsertTestCampaignVideoRequestPlatform } from './upsertTestCampaignVideoRequestPlatform';
import type { UpsertTestCampaignVideoRequestStatus } from './upsertTestCampaignVideoRequestStatus';

export interface UpsertTestCampaignVideoRequest {
  campaign_id: string;
  brand_workspace_id: string;
  creator_account_id: string;
  platform: UpsertTestCampaignVideoRequestPlatform;
  /** Optional stable key. Without it, idempotency uses campaign_id + creator_account_id + platform + url. */
  fixture_key?: string;
  url: string;
  format?: string;
  status?: UpsertTestCampaignVideoRequestStatus;
  offer_id?: string;
  s3_key?: string;
  thumbnail_s3_key?: string;
  /** @minimum 0 */
  duration_sec?: number;
  mime_type?: string;
  original_filename?: string;
  /** @minimum 1 */
  file_size_bytes?: number;
  submitted_at?: string;
  preview_title?: string;
  preview_description?: string;
  preview_image_url?: string;
  preview_site_name?: string;
  preview_resolved_at?: string;
}
