/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Marz Test API
 * Test-only contract for E2E fixtures. All endpoints require `X-Test-Secret`
and are gated by `TEST_API_ENABLED=true`. Never available in production.

Consumed by marz-front E2E suite via a separate Orval generation target so
the production client stays free of test-only types.

 * OpenAPI spec version: 0.1.0
 */
import type { UpsertTestCampaignParticipantRequestCurrentPlatformsItem } from './upsertTestCampaignParticipantRequestCurrentPlatformsItem';
import type { UpsertTestCampaignParticipantRequestSource } from './upsertTestCampaignParticipantRequestSource';
import type { UpsertTestCampaignParticipantRequestStatus } from './upsertTestCampaignParticipantRequestStatus';

export interface UpsertTestCampaignParticipantRequest {
  campaign_id: string;
  brand_workspace_id: string;
  creator_account_id: string;
  current_platforms: UpsertTestCampaignParticipantRequestCurrentPlatformsItem[];
  status?: UpsertTestCampaignParticipantRequestStatus;
  source?: UpsertTestCampaignParticipantRequestSource;
  /** @minimum 0 */
  deliverables_expected?: number;
  /** @minimum 0 */
  deliverables_completed?: number;
  conversation_id?: string;
  latest_offer_id?: string;
  first_joined_at?: string;
  last_activity_at?: string;
}
