/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Marz Test API
 * Test-only contract for E2E fixtures. All endpoints require `X-Test-Secret`
and are gated by `TEST_API_ENABLED=true`. Never available in production.

Consumed by marz-front E2E suite via a separate Orval generation target so
the production client stays free of test-only types.

 * OpenAPI spec version: 0.1.0
 */
import type { UpsertTestCampaignRequestBonusConfig } from './upsertTestCampaignRequestBonusConfig';
import type { UpsertTestCampaignRequestConfigurationCompletedStepsItem } from './upsertTestCampaignRequestConfigurationCompletedStepsItem';
import type { UpsertTestCampaignRequestConfigurationCurrentStep } from './upsertTestCampaignRequestConfigurationCurrentStep';
import type { UpsertTestCampaignRequestContentType } from './upsertTestCampaignRequestContentType';
import type { UpsertTestCampaignRequestObjective } from './upsertTestCampaignRequestObjective';
import type { UpsertTestCampaignRequestOperationalTargeting } from './upsertTestCampaignRequestOperationalTargeting';
import type { UpsertTestCampaignRequestPricingModel } from './upsertTestCampaignRequestPricingModel';
import type { UpsertTestCampaignRequestStatus } from './upsertTestCampaignRequestStatus';

export interface UpsertTestCampaignRequest {
  brand_workspace_id: string;
  /** Stable explicit campaign id. Required when campaign_key is absent. */
  campaign_id?: string;
  /**
     * Stable key scoped by brand_workspace_id. Required when campaign_id is absent.
     * @minLength 1
     */
  campaign_key?: string;
  name?: string;
  objective?: UpsertTestCampaignRequestObjective;
  budget_amount?: string;
  /**
     * @minLength 3
     * @maxLength 3
     */
  budget_currency?: string;
  deadline?: string;
  status?: UpsertTestCampaignRequestStatus;
  content_type?: UpsertTestCampaignRequestContentType;
  pricing_model?: UpsertTestCampaignRequestPricingModel;
  target_platforms?: string[];
  configuration_completed_steps?: UpsertTestCampaignRequestConfigurationCompletedStepsItem[];
  configuration_current_step?: UpsertTestCampaignRequestConfigurationCurrentStep;
  configuration_completed_at?: string;
  operational_targeting?: UpsertTestCampaignRequestOperationalTargeting;
  bonus_config?: UpsertTestCampaignRequestBonusConfig;
  read_dependencies?: boolean;
}
