/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Marz Test API
 * Test-only contract for E2E fixtures. All endpoints require `X-Test-Secret`
and are gated by `TEST_API_ENABLED=true`. Never available in production.

Consumed by marz-front E2E suite via a separate Orval generation target so
the production client stays free of test-only types.

 * OpenAPI spec version: 0.1.0
 */
import type {
  CreateTestAccountRequest,
  CreateTestConversationRequest,
  CreateTestConversationResponse,
  Error,
  MeResponse,
  OnboardTestAccountFullRequest,
  PurgeTestAccountsRequest,
  PurgeTestAccountsResponse,
  SetTestOnboardingRequest,
} from '../model'

import { testFetch } from '../../test-mutator'

/**
 * Creates a test account or returns an existing one matched by clerk_user_id.

Email is UNIQUE. If the email already belongs to another `is_test=true`
account (zombie from a prior run that crashed before cleanup), the
zombie is hard-deleted and the slot is reused with the new
clerk_user_id. If the email belongs to a non-test account the request
is rejected with 500 (production data is never touched).

 */
export type createTestAccountResponse200 = {
  data: MeResponse
  status: 200
}

export type createTestAccountResponse400 = {
  data: Error
  status: 400
}

export type createTestAccountResponse401 = {
  data: Error
  status: 401
}

export type createTestAccountResponse500 = {
  data: Error
  status: 500
}

export type createTestAccountResponseSuccess = createTestAccountResponse200 & {
  headers: Headers
}
export type createTestAccountResponseError = (
  | createTestAccountResponse400
  | createTestAccountResponse401
  | createTestAccountResponse500
) & {
  headers: Headers
}

export type createTestAccountResponse =
  | createTestAccountResponseSuccess
  | createTestAccountResponseError

export const getCreateTestAccountUrl = () => {
  return `/v1/test/accounts`
}

export const createTestAccount = async (
  createTestAccountRequest: CreateTestAccountRequest,
  options?: RequestInit,
): Promise<createTestAccountResponse> => {
  return testFetch<createTestAccountResponse>(getCreateTestAccountUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createTestAccountRequest),
  })
}

/**
 * Hard-deletes every is_test account whose email matches the SQL LIKE
pattern (and cascades to chat / identity dependents per the per-account
path). Always scoped to is_test=true, so production rows are never
touched.

The pattern must contain at least one SQL wildcard (`%` or `_`) to
prevent accidental scope blow-up. Returns the number of accounts
deleted. Use this as an escape hatch when zombies from prior runs
block fresh fixtures.

 */
export type purgeTestAccountsResponse200 = {
  data: PurgeTestAccountsResponse
  status: 200
}

export type purgeTestAccountsResponse400 = {
  data: Error
  status: 400
}

export type purgeTestAccountsResponse401 = {
  data: Error
  status: 401
}

export type purgeTestAccountsResponse500 = {
  data: Error
  status: 500
}

export type purgeTestAccountsResponseSuccess = purgeTestAccountsResponse200 & {
  headers: Headers
}
export type purgeTestAccountsResponseError = (
  | purgeTestAccountsResponse400
  | purgeTestAccountsResponse401
  | purgeTestAccountsResponse500
) & {
  headers: Headers
}

export type purgeTestAccountsResponse =
  | purgeTestAccountsResponseSuccess
  | purgeTestAccountsResponseError

export const getPurgeTestAccountsUrl = () => {
  return `/v1/test/accounts:purge`
}

export const purgeTestAccounts = async (
  purgeTestAccountsRequest: PurgeTestAccountsRequest,
  options?: RequestInit,
): Promise<purgeTestAccountsResponse> => {
  return testFetch<purgeTestAccountsResponse>(getPurgeTestAccountsUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(purgeTestAccountsRequest),
  })
}

/**
 * Forces a test account into a specific onboarding state.

 */
export type setTestOnboardingStateResponse200 = {
  data: MeResponse
  status: 200
}

export type setTestOnboardingStateResponse400 = {
  data: Error
  status: 400
}

export type setTestOnboardingStateResponse401 = {
  data: Error
  status: 401
}

export type setTestOnboardingStateResponse404 = {
  data: Error
  status: 404
}

export type setTestOnboardingStateResponse500 = {
  data: Error
  status: 500
}

export type setTestOnboardingStateResponseSuccess =
  setTestOnboardingStateResponse200 & {
    headers: Headers
  }
export type setTestOnboardingStateResponseError = (
  | setTestOnboardingStateResponse400
  | setTestOnboardingStateResponse401
  | setTestOnboardingStateResponse404
  | setTestOnboardingStateResponse500
) & {
  headers: Headers
}

export type setTestOnboardingStateResponse =
  | setTestOnboardingStateResponseSuccess
  | setTestOnboardingStateResponseError

export const getSetTestOnboardingStateUrl = (clerkUserId: string) => {
  return `/v1/test/accounts/${clerkUserId}/onboarding`
}

export const setTestOnboardingState = async (
  clerkUserId: string,
  setTestOnboardingRequest: SetTestOnboardingRequest,
  options?: RequestInit,
): Promise<setTestOnboardingStateResponse> => {
  return testFetch<setTestOnboardingStateResponse>(
    getSetTestOnboardingStateUrl(clerkUserId),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(setTestOnboardingRequest),
    },
  )
}

/**
 * Marks the account as fully onboarded for the requested kind AND seeds
the side effects production onboarding would create:

- kind=brand → creates an `identity_brand_workspaces` row + an owner
  `identity_brand_memberships` row.
- kind=creator → creates an `identity_creator_profiles` row with
  minimum valid content (niches=["general"], empty content_types and
  best_videos).

Idempotent: re-running on an already-onboarded test account does not
duplicate workspaces or profiles.

Use this endpoint when the test needs an account ready for chat,
offers, etc. Use the simpler `/onboarding` endpoint when the test
needs to assert behavior at a specific onboarding state.

 */
export type onboardTestAccountFullResponse200 = {
  data: MeResponse
  status: 200
}

export type onboardTestAccountFullResponse400 = {
  data: Error
  status: 400
}

export type onboardTestAccountFullResponse401 = {
  data: Error
  status: 401
}

export type onboardTestAccountFullResponse404 = {
  data: Error
  status: 404
}

export type onboardTestAccountFullResponse500 = {
  data: Error
  status: 500
}

export type onboardTestAccountFullResponseSuccess =
  onboardTestAccountFullResponse200 & {
    headers: Headers
  }
export type onboardTestAccountFullResponseError = (
  | onboardTestAccountFullResponse400
  | onboardTestAccountFullResponse401
  | onboardTestAccountFullResponse404
  | onboardTestAccountFullResponse500
) & {
  headers: Headers
}

export type onboardTestAccountFullResponse =
  | onboardTestAccountFullResponseSuccess
  | onboardTestAccountFullResponseError

export const getOnboardTestAccountFullUrl = (clerkUserId: string) => {
  return `/v1/test/accounts/${clerkUserId}/onboard-full`
}

export const onboardTestAccountFull = async (
  clerkUserId: string,
  onboardTestAccountFullRequest: OnboardTestAccountFullRequest,
  options?: RequestInit,
): Promise<onboardTestAccountFullResponse> => {
  return testFetch<onboardTestAccountFullResponse>(
    getOnboardTestAccountFullUrl(clerkUserId),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(onboardTestAccountFullRequest),
    },
  )
}

/**
 * Creates (or returns existing) chat conversation for the brand↔creator pair.
Bypasses the production trigger flow (invite/application acceptance).
Optionally seeds deterministic text messages for history/scroll tests.

Idempotent: if a conversation already exists for the pair it is returned.
Seed messages, when requested, are appended on top of any existing ones.

 */
export type createTestConversationResponse200 = {
  data: CreateTestConversationResponse
  status: 200
}

export type createTestConversationResponse400 = {
  data: Error
  status: 400
}

export type createTestConversationResponse401 = {
  data: Error
  status: 401
}

export type createTestConversationResponse404 = {
  data: Error
  status: 404
}

export type createTestConversationResponse409 = {
  data: Error
  status: 409
}

export type createTestConversationResponse500 = {
  data: Error
  status: 500
}

export type createTestConversationResponseSuccess =
  createTestConversationResponse200 & {
    headers: Headers
  }
export type createTestConversationResponseError = (
  | createTestConversationResponse400
  | createTestConversationResponse401
  | createTestConversationResponse404
  | createTestConversationResponse409
  | createTestConversationResponse500
) & {
  headers: Headers
}

export type createTestConversationResponse =
  | createTestConversationResponseSuccess
  | createTestConversationResponseError

export const getCreateTestConversationUrl = () => {
  return `/v1/test/conversations`
}

export const createTestConversation = async (
  createTestConversationRequest: CreateTestConversationRequest,
  options?: RequestInit,
): Promise<createTestConversationResponse> => {
  return testFetch<createTestConversationResponse>(
    getCreateTestConversationUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(createTestConversationRequest),
    },
  )
}

/**
 * Hard-deletes a test account and cascades to brand_workspace_memberships,
brand_workspaces (when the account was the last member), creator_profiles,
chat conversations, and chat messages owned by the account.

Idempotent: returns 204 even when the account does not exist.

 */
export type deleteTestAccountResponse204 = {
  data: void
  status: 204
}

export type deleteTestAccountResponse401 = {
  data: Error
  status: 401
}

export type deleteTestAccountResponse500 = {
  data: Error
  status: 500
}

export type deleteTestAccountResponseSuccess = deleteTestAccountResponse204 & {
  headers: Headers
}
export type deleteTestAccountResponseError = (
  | deleteTestAccountResponse401
  | deleteTestAccountResponse500
) & {
  headers: Headers
}

export type deleteTestAccountResponse =
  | deleteTestAccountResponseSuccess
  | deleteTestAccountResponseError

export const getDeleteTestAccountUrl = (clerkUserId: string) => {
  return `/v1/test/accounts/${clerkUserId}`
}

export const deleteTestAccount = async (
  clerkUserId: string,
  options?: RequestInit,
): Promise<deleteTestAccountResponse> => {
  return testFetch<deleteTestAccountResponse>(
    getDeleteTestAccountUrl(clerkUserId),
    {
      ...options,
      method: 'DELETE',
    },
  )
}
