import type { UseQueryOptions, UseQueryResult } from '@tanstack/react-query'

import {
  useGetCampaignQuota,
  useGetDiscoveryCreatorCount,
} from '#/shared/api/generated/brand/brand'
import type {
  getCampaignQuotaResponse,
  getDiscoveryCreatorCountResponse,
} from '#/shared/api/generated/brand/brand'
import {
  useListCountries,
  useListCreatorTiers,
  useListInterests,
} from '#/shared/api/generated/lookups/lookups'
import type {
  listCountriesResponse,
  listCreatorTiersResponse,
  listInterestsResponse,
} from '#/shared/api/generated/lookups/lookups'
import type {
  ErrorResponse,
  GetDiscoveryCreatorCountParams,
  ListCountriesParams,
  SocialPlatform,
} from '#/shared/api/generated/model'

export type CreatorCountFilters = {
  platforms: SocialPlatform[]
  interests: string[]
  creator_country: string | null
  min_creator_tier_slug: string | null
}

type QueryOptions<TResponse> = {
  query?: Partial<UseQueryOptions<TResponse, ErrorResponse, TResponse>>
  request?: RequestInit
}

export function useCampaignQuotaQuery(
  brandWorkspaceId: string | null | undefined,
  options?: QueryOptions<getCampaignQuotaResponse>,
): UseQueryResult<getCampaignQuotaResponse, ErrorResponse> & {
  queryKey: readonly unknown[]
} {
  const queryOptions = options?.query
  return useGetCampaignQuota(brandWorkspaceId ?? '', {
    request: options?.request,
    query: {
      ...queryOptions,
      enabled: Boolean(brandWorkspaceId) && (queryOptions?.enabled ?? true),
    },
  })
}

export function useInterestsQuery(
  options?: QueryOptions<listInterestsResponse>,
): UseQueryResult<listInterestsResponse, ErrorResponse> & {
  queryKey: readonly unknown[]
} {
  return useListInterests(options)
}

export function useCountriesQuery(
  params?: ListCountriesParams,
  options?: QueryOptions<listCountriesResponse>,
): UseQueryResult<listCountriesResponse, ErrorResponse> & {
  queryKey: readonly unknown[]
} {
  return useListCountries(params, options)
}

export function useCreatorTiersQuery(
  options?: QueryOptions<listCreatorTiersResponse>,
): UseQueryResult<listCreatorTiersResponse, ErrorResponse> & {
  queryKey: readonly unknown[]
} {
  return useListCreatorTiers(options)
}

export function useCreatorCountQuery(
  filters: CreatorCountFilters,
  options?: QueryOptions<getDiscoveryCreatorCountResponse>,
): UseQueryResult<getDiscoveryCreatorCountResponse, ErrorResponse> & {
  queryKey: readonly unknown[]
} {
  const params = toCreatorCountParams(filters)
  const queryOptions = options?.query

  return useGetDiscoveryCreatorCount(params ?? disabledCreatorCountParams, {
    request: options?.request,
    query: {
      ...queryOptions,
      enabled: Boolean(params) && (queryOptions?.enabled ?? true),
    },
  })
}

export function toCreatorCountParams(
  filters: CreatorCountFilters,
): GetDiscoveryCreatorCountParams | null {
  if (
    filters.platforms.length === 0 ||
    filters.interests.length === 0 ||
    !filters.creator_country ||
    !filters.min_creator_tier_slug
  ) {
    return null
  }

  return {
    platforms: filters.platforms,
    interests: filters.interests,
    // The wizard store keeps this as `creator_country`; the API query
    // parameter generated by Orval is `country`.
    country: filters.creator_country,
    min_creator_tier_slug: filters.min_creator_tier_slug,
  }
}

const disabledCreatorCountParams: GetDiscoveryCreatorCountParams = {
  platforms: ['instagram'],
  interests: ['disabled'],
  country: 'AR',
  min_creator_tier_slug: 'disabled',
}
